### ISSUE TITLE
Region selector not working in IE

### ISSUE THREAD

**Issue by PaulScala** [benkeen/react-country-region-selector#20]
Hi, 

I noticed that any page that has the region selector included is not rendering properly in IE 11 and will break the page. The react country selector demos at [http://benkeen.github.io/react-country-region-selector/](http://benkeen.github.io/react-country-region-selector/) are breaking in IE 11 too. 

On the website I am developing I am getting the following error in the IE console: 

> Unable to get property 'nextSibling' of undefined or null reference

Any ideas on how I can work around this?

**Comment by manushah** [comment]
Hi,

Any updates or workaround for this issue ?

**Comment by benkeen** [comment]
Hi guys - sorry for not getting back to you sooner. Let me take a look at this. Keep you posted.

**Comment by benkeen** [comment]
Thanks for posting the bug @PaulScala  - and reminding me @manushah! 

I just released 1.2.1. The demos now work properly on IE11. It was my mistake; I forgot that array.find() wasn't standardized and not part of IE 11. All patched now! 

http://benkeen.github.io/react-country-region-selector/

**Comment by PaulScala** [comment]
@benkeen Thanks for the fix! I can confirm it is working now correctly for me in IE. This will make quite a few people I am working with happy. Granted I still don't understand why people would chose to use IE.
